name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --global pnpm
      - run: pnpm i
      - run: npm run build
      # - run: npm publish --provenance --access public -w ./packages/studio-base --tag next
      - run: npm publish --provenance --access public -w ./packages/studio-base
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --provenance --access public -w ./packages/studio
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
